spring:
  application:
    name: order-service
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS}

server:
  port: 8082

#enable this when we used eureka service
#eureka:
#  client:
#    service-url:
#      defaultZone: http://service-registry:8761/eureka/
#
#  instance:
#    prefer-ip-address: true
#    non-secure-port: 8082
