spring:
  application:
    name: order-service

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://service-registry:8761/eureka/

  instance:
    prefer-ip-address: true
    non-secure-port: 8080
